language: node_js
node_js:
- 8
script:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: _
  file: com.siemens.bt.jazz.workitemeditor.rtcPrintWorkItemAction*.zip
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: jazz-community/rtc-print-workitem-action
